{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<font color='pink'>**Summative Assignment - Nicole Ben Haim & Noam Ifargan**</font>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np \n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "%matplotlib inline\n",
    "import re\n",
    "import pandas as pd\n",
    "import numpy as np \n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import datetime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "datafile = 'C://Users/noami/Desktop/Summative Assignment/output_all_students_Train_v10.xlsx'\n",
    "data1 = pd.read_excel(datafile)\n",
    "data = data1.copy()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<font color='red'>**STEP 1 - data cleaning and preparation**</font>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "1. Delete properties with missing prices - \n",
    "Remove properties from the dataset where the price is missing."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>City</th>\n",
       "      <th>type</th>\n",
       "      <th>room_number</th>\n",
       "      <th>Area</th>\n",
       "      <th>Street</th>\n",
       "      <th>number_in_street</th>\n",
       "      <th>city_area</th>\n",
       "      <th>price</th>\n",
       "      <th>num_of_images</th>\n",
       "      <th>floor_out_of</th>\n",
       "      <th>...</th>\n",
       "      <th>hasStorage</th>\n",
       "      <th>condition</th>\n",
       "      <th>hasAirCondition</th>\n",
       "      <th>hasBalcony</th>\n",
       "      <th>hasMamad</th>\n",
       "      <th>handicapFriendly</th>\n",
       "      <th>entranceDate</th>\n",
       "      <th>furniture</th>\n",
       "      <th>publishedDays</th>\n",
       "      <th>description</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>5.5</td>\n",
       "      <td>137</td>\n",
       "      <td>רפאלי שרגא</td>\n",
       "      <td>3</td>\n",
       "      <td>אם המושבות החדשה</td>\n",
       "      <td>3600000</td>\n",
       "      <td>6.0</td>\n",
       "      <td>קומה 11 מתוך 19</td>\n",
       "      <td>...</td>\n",
       "      <td>False</td>\n",
       "      <td>שמור</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>7</td>\n",
       "      <td>למכירה 5.5 חדרים ענקית, מרווחת , מוארת , קומה ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>3</td>\n",
       "      <td>84</td>\n",
       "      <td>כצנלסון אהרון</td>\n",
       "      <td>6</td>\n",
       "      <td>נווה גן</td>\n",
       "      <td>2550000</td>\n",
       "      <td>6.0</td>\n",
       "      <td>קומה 6 מתוך 9</td>\n",
       "      <td>...</td>\n",
       "      <td>True</td>\n",
       "      <td>שמור</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>מיידי</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>8</td>\n",
       "      <td>למכירה מפרטי ברחוב אהרון כצנלסון השקט והמבוקש,...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>4</td>\n",
       "      <td>120</td>\n",
       "      <td>הירקונים</td>\n",
       "      <td>17</td>\n",
       "      <td>קרית הרב סלומון</td>\n",
       "      <td>2650000</td>\n",
       "      <td>10.0</td>\n",
       "      <td>קומה 2 מתוך 7</td>\n",
       "      <td>...</td>\n",
       "      <td>True</td>\n",
       "      <td>חדש</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>חלקי</td>\n",
       "      <td>6</td>\n",
       "      <td>פריים לוקשיין בשכונת שיפר המאוד מבוקשת!!! למכי...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>3.5</td>\n",
       "      <td>110</td>\n",
       "      <td>סלנט שמואל</td>\n",
       "      <td>56</td>\n",
       "      <td>המרכז השקט</td>\n",
       "      <td>2450000</td>\n",
       "      <td>8.0</td>\n",
       "      <td>קומה 2 מתוך 6</td>\n",
       "      <td>...</td>\n",
       "      <td>False</td>\n",
       "      <td>משופץ</td>\n",
       "      <td>True</td>\n",
       "      <td>False</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>חלקי</td>\n",
       "      <td>8</td>\n",
       "      <td>בפתח תקווה ברחוב שמואל סלנט המבוקש,לא כדאי לפס...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>4.5</td>\n",
       "      <td>120</td>\n",
       "      <td>בן צבי יצחק</td>\n",
       "      <td>28</td>\n",
       "      <td>כפר גנים ב</td>\n",
       "      <td>2720000</td>\n",
       "      <td>9.0</td>\n",
       "      <td>קומה 3 מתוך 6</td>\n",
       "      <td>...</td>\n",
       "      <td>False</td>\n",
       "      <td>משופץ</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>True</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>21</td>\n",
       "      <td>הדירה משופצת חלקית בטעם טוב , פונה לעורף לכיוו...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>694</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>בית פרטי</td>\n",
       "      <td>9.5 חד׳</td>\n",
       "      <td>350 מ\"ר</td>\n",
       "      <td>הורד</td>\n",
       "      <td>35</td>\n",
       "      <td>2005</td>\n",
       "      <td>8200000</td>\n",
       "      <td>NaN</td>\n",
       "      <td>קומה 4 מתוך 4</td>\n",
       "      <td>...</td>\n",
       "      <td>יש מחסן</td>\n",
       "      <td>שמור</td>\n",
       "      <td>יש מיזוג אויר</td>\n",
       "      <td>יש מרפסת</td>\n",
       "      <td>יש ממ״ד</td>\n",
       "      <td>לא נגיש לנכים</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>אין</td>\n",
       "      <td>NaN</td>\n",
       "      <td>בית גדול מאוד , 3 כיווני אוויר , 2 מרפסות גדולות</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>695</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>4 חד׳</td>\n",
       "      <td>110 מ\"ר</td>\n",
       "      <td>קזן</td>\n",
       "      <td>NaN</td>\n",
       "      <td>מרכז דרום</td>\n",
       "      <td>3350000</td>\n",
       "      <td>6.0</td>\n",
       "      <td>קומה 4 מתוך 6</td>\n",
       "      <td>...</td>\n",
       "      <td>יש מחסן</td>\n",
       "      <td>חדש</td>\n",
       "      <td>יש מיזוג אויר</td>\n",
       "      <td>יש מרפסת</td>\n",
       "      <td>יש ממ״ד</td>\n",
       "      <td>נגיש לנכים</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>NaN</td>\n",
       "      <td>בקומה 4 הדירה 110 מ\"ר נטו136 מ\"ר ארנונה.מעוצבת...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>696</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>קוטג'</td>\n",
       "      <td>7 חד׳</td>\n",
       "      <td>376 מ\"ר</td>\n",
       "      <td>הטללים</td>\n",
       "      <td>NaN</td>\n",
       "      <td>קרית גנים</td>\n",
       "      <td>8500000</td>\n",
       "      <td>13.0</td>\n",
       "      <td>קומת קרקע</td>\n",
       "      <td>...</td>\n",
       "      <td>אין מחסן</td>\n",
       "      <td>חדש</td>\n",
       "      <td>אין מיזוג אויר</td>\n",
       "      <td>אין מרפסת</td>\n",
       "      <td>אין ממ״ד</td>\n",
       "      <td>לא נגיש לנכים</td>\n",
       "      <td>2023-08-01 00:00:00</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>NaN</td>\n",
       "      <td>במערב המבוקש! !ה---- בית הנדיר הזה הוא עוד אחד...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>697</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>5 חד׳</td>\n",
       "      <td>126 מ\"ר</td>\n",
       "      <td>אחד העם</td>\n",
       "      <td>NaN</td>\n",
       "      <td>לסטר</td>\n",
       "      <td>3850000</td>\n",
       "      <td>NaN</td>\n",
       "      <td>קומה 5 מתוך 7</td>\n",
       "      <td>...</td>\n",
       "      <td>אין מחסן</td>\n",
       "      <td>חדש</td>\n",
       "      <td>יש מיזוג אויר</td>\n",
       "      <td>יש מרפסת</td>\n",
       "      <td>יש ממ״ד</td>\n",
       "      <td>נגיש לנכים</td>\n",
       "      <td>מיידי</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>NaN</td>\n",
       "      <td>דירה חדשה מהקבלן באזור מבוקש .\\n5 חדרים .מרווח...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>698</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>4.5 חד׳</td>\n",
       "      <td>140 מ\"ר</td>\n",
       "      <td>קזן</td>\n",
       "      <td>10</td>\n",
       "      <td>מרכז דרום</td>\n",
       "      <td>3730000</td>\n",
       "      <td>6.0</td>\n",
       "      <td>קומה 3 מתוך 6</td>\n",
       "      <td>...</td>\n",
       "      <td>יש מחסן</td>\n",
       "      <td>משופץ</td>\n",
       "      <td>יש מיזוג אויר</td>\n",
       "      <td>יש מרפסת</td>\n",
       "      <td>יש ממ״ד</td>\n",
       "      <td>נגיש לנכים</td>\n",
       "      <td>2024-02-01 00:00:00</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>NaN</td>\n",
       "      <td>לא למתווכים!, ללא תיווך!, מתווכים לא להתקשר! ד...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>694 rows × 23 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          City      type room_number     Area         Street number_in_street  \\\n",
       "0    פתח תקווה      דירה         5.5      137     רפאלי שרגא                3   \n",
       "1    פתח תקווה      דירה           3       84  כצנלסון אהרון                6   \n",
       "2    פתח תקווה      דירה           4      120       הירקונים               17   \n",
       "3    פתח תקווה      דירה         3.5      110     סלנט שמואל               56   \n",
       "4    פתח תקווה      דירה         4.5      120    בן צבי יצחק               28   \n",
       "..         ...       ...         ...      ...            ...              ...   \n",
       "694      רעננה  בית פרטי     9.5 חד׳  350 מ\"ר           הורד               35   \n",
       "695      רעננה      דירה       4 חד׳  110 מ\"ר            קזן              NaN   \n",
       "696      רעננה     קוטג'       7 חד׳  376 מ\"ר         הטללים              NaN   \n",
       "697      רעננה      דירה       5 חד׳  126 מ\"ר        אחד העם              NaN   \n",
       "698      רעננה      דירה     4.5 חד׳  140 מ\"ר            קזן               10   \n",
       "\n",
       "            city_area    price  num_of_images     floor_out_of  ...  \\\n",
       "0    אם המושבות החדשה  3600000            6.0  קומה 11 מתוך 19  ...   \n",
       "1             נווה גן  2550000            6.0    קומה 6 מתוך 9  ...   \n",
       "2     קרית הרב סלומון  2650000           10.0    קומה 2 מתוך 7  ...   \n",
       "3          המרכז השקט  2450000            8.0    קומה 2 מתוך 6  ...   \n",
       "4          כפר גנים ב  2720000            9.0    קומה 3 מתוך 6  ...   \n",
       "..                ...      ...            ...              ...  ...   \n",
       "694              2005  8200000            NaN    קומה 4 מתוך 4  ...   \n",
       "695         מרכז דרום  3350000            6.0    קומה 4 מתוך 6  ...   \n",
       "696         קרית גנים  8500000           13.0        קומת קרקע  ...   \n",
       "697              לסטר  3850000            NaN    קומה 5 מתוך 7  ...   \n",
       "698         מרכז דרום  3730000            6.0    קומה 3 מתוך 6  ...   \n",
       "\n",
       "    hasStorage  condition  hasAirCondition  hasBalcony  hasMamad   \\\n",
       "0         False       שמור             True       False      True   \n",
       "1          True       שמור             True       False      True   \n",
       "2          True        חדש             True        True      True   \n",
       "3         False      משופץ             True       False      True   \n",
       "4         False      משופץ             True        True      True   \n",
       "..          ...        ...              ...         ...       ...   \n",
       "694     יש מחסן       שמור    יש מיזוג אויר    יש מרפסת   יש ממ״ד   \n",
       "695     יש מחסן        חדש    יש מיזוג אויר    יש מרפסת   יש ממ״ד   \n",
       "696    אין מחסן        חדש   אין מיזוג אויר   אין מרפסת  אין ממ״ד   \n",
       "697    אין מחסן        חדש    יש מיזוג אויר    יש מרפסת   יש ממ״ד   \n",
       "698     יש מחסן      משופץ    יש מיזוג אויר    יש מרפסת   יש ממ״ד   \n",
       "\n",
       "    handicapFriendly         entranceDate  furniture  publishedDays   \\\n",
       "0                True                 גמיש   לא צויין              7   \n",
       "1               False                מיידי   לא צויין              8   \n",
       "2               False                 גמיש       חלקי              6   \n",
       "3                True                 גמיש       חלקי              8   \n",
       "4                True                 גמיש   לא צויין             21   \n",
       "..                ...                  ...        ...            ...   \n",
       "694     לא נגיש לנכים                 גמיש        אין            NaN   \n",
       "695        נגיש לנכים                 גמיש   לא צויין            NaN   \n",
       "696     לא נגיש לנכים  2023-08-01 00:00:00   לא צויין            NaN   \n",
       "697        נגיש לנכים                מיידי   לא צויין            NaN   \n",
       "698        נגיש לנכים  2024-02-01 00:00:00   לא צויין            NaN   \n",
       "\n",
       "                                          description   \n",
       "0    למכירה 5.5 חדרים ענקית, מרווחת , מוארת , קומה ...  \n",
       "1    למכירה מפרטי ברחוב אהרון כצנלסון השקט והמבוקש,...  \n",
       "2    פריים לוקשיין בשכונת שיפר המאוד מבוקשת!!! למכי...  \n",
       "3    בפתח תקווה ברחוב שמואל סלנט המבוקש,לא כדאי לפס...  \n",
       "4    הדירה משופצת חלקית בטעם טוב , פונה לעורף לכיוו...  \n",
       "..                                                 ...  \n",
       "694   בית גדול מאוד , 3 כיווני אוויר , 2 מרפסות גדולות  \n",
       "695  בקומה 4 הדירה 110 מ\"ר נטו136 מ\"ר ארנונה.מעוצבת...  \n",
       "696  במערב המבוקש! !ה---- בית הנדיר הזה הוא עוד אחד...  \n",
       "697  דירה חדשה מהקבלן באזור מבוקש .\\n5 חדרים .מרווח...  \n",
       "698  לא למתווכים!, ללא תיווך!, מתווכים לא להתקשר! ד...  \n",
       "\n",
       "[694 rows x 23 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = data.dropna(subset=['price'])\n",
    "data"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "2+3. Ensure that the price  and area is numeric:\n",
    "Keep only the numeric values for the price column and Convert the price values to a numeric data type.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-4-2f7f79d3a24d>:17: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['Area'] = data['Area'].apply(clean_price_and_Area).replace('', np.nan)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "array(['137', '84', '120', '110', '98', '140', '147', '100', '75', '95',\n",
       "       '125', '121', '55', '70', '145', '62', '93', '108', '49', '150',\n",
       "       '130', '104', nan, '78', '270', '90', '96', '135', '80', '118',\n",
       "       '119', '148', '52', '54', '182', '85', '300', '53', '122', '76',\n",
       "       '160', '123', '144', '83', '73', '127', '151', '184', '134', '152',\n",
       "       '74', '64', '67', '65', '138', '46', '139', '79', '92', '68',\n",
       "       '146', '103', '106', '132', '105', '117', '175', '99', '225',\n",
       "       '113', '112', '60', '220', '126', '128', '114', '167', '94', '355',\n",
       "       '172', '235', '174', '143', '200', '280', '250', '136', '109',\n",
       "       '330', '180', '45', '240', '40', '89', '157', '173', '170', '176',\n",
       "       '77', '50', '141', '124', '286', '81', '1000', '318', '86', '102',\n",
       "       '116', '155', '131', '42', '111', '165', '56', '339', '504', '101',\n",
       "       '91', '115', '57', '71', '319', '87', '30', '69', '97', '208',\n",
       "       '350', '234', '161', '260', '82', '142', '129', '156', '107', '88',\n",
       "       '315', '380', '158', '72', '154', '48', '159', '63', '58', '149',\n",
       "       '153', '376'], dtype=object)"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def clean_price_and_Area(x):\n",
    "    if isinstance(x, str):\n",
    "        x = re.sub(r'[^\\d,]', '', x)  # מחיקת תווים שאינם ספרות או פסיק\n",
    "        return x.replace(',', '')  # הסרת פסיקים\n",
    "    elif isinstance(x, int):\n",
    "        return str(x)  # חיזור ערך מספרי כמחרוזת\n",
    "    else:\n",
    "        return ''\n",
    "    \n",
    "#ניקוי עמודת המחיר   \n",
    "data['price'] = data['price'].apply(clean_price_and_Area).replace('', np.nan)\n",
    "data = data.dropna(subset=['price'])\n",
    "unique_price = data['price'].unique()\n",
    "unique_price\n",
    "\n",
    "#ניקוי עמודת השטח\n",
    "data['Area'] = data['Area'].apply(clean_price_and_Area).replace('', np.nan)\n",
    "unique_Area = data['Area'].unique()\n",
    "unique_Area"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.series.Series'>\n",
      "Int64Index: 693 entries, 0 to 698\n",
      "Series name: price\n",
      "Non-Null Count  Dtype\n",
      "--------------  -----\n",
      "693 non-null    int32\n",
      "dtypes: int32(1)\n",
      "memory usage: 8.1 KB\n",
      "<class 'pandas.core.series.Series'>\n",
      "Int64Index: 693 entries, 0 to 698\n",
      "Series name: Area\n",
      "Non-Null Count  Dtype\n",
      "--------------  -----\n",
      "677 non-null    Int64\n",
      "dtypes: Int64(1)\n",
      "memory usage: 11.5 KB\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-5-d8bf79847379>:2: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['price'] = data['price'].astype(int)\n",
      "<ipython-input-5-d8bf79847379>:4: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['Area'] = pd.to_numeric(data['Area'], errors='coerce').fillna(data['Area'])\n",
      "<ipython-input-5-d8bf79847379>:5: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['Area'] = pd.to_numeric(data['Area'], errors='coerce').astype('Int64')\n"
     ]
    }
   ],
   "source": [
    "#המרת השדות לערך מספרי\n",
    "data['price'] = data['price'].astype(int)\n",
    "data['price'].info()\n",
    "data['Area'] = pd.to_numeric(data['Area'], errors='coerce').fillna(data['Area'])\n",
    "data['Area'] = pd.to_numeric(data['Area'], errors='coerce').astype('Int64')\n",
    "data['Area'].info()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "4. Remove unnecessary punctuation from text fields:\n",
    "\n",
    "Remove excessive commas or other unnecessary punctuation marks from address, region, property description, etc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-6-950d2137068a>:11: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['Street']=data['Street'].apply(lambda x: word(x))\n",
      "<ipython-input-6-950d2137068a>:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['city_area']=data['city_area'].apply(lambda x: word(x))\n",
      "<ipython-input-6-950d2137068a>:13: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['description ']=data['description '].apply(lambda x: word(x))\n"
     ]
    }
   ],
   "source": [
    "def word(x):\n",
    "    if isinstance(x, str):\n",
    "        x = re.sub(r'[^\\w /.]', '', x)  # מחיקת תווים שאינם ספרות או פסיק\n",
    "        x=x.replace('/',' ')\n",
    "        x=x.replace('.',' ')\n",
    "        x=x.replace('  ',' ')\n",
    "        return x.strip()\n",
    "    else:\n",
    "        return ''\n",
    "\n",
    "data['Street']=data['Street'].apply(lambda x: word(x))\n",
    "data['city_area']=data['city_area'].apply(lambda x: word(x))\n",
    "data['description ']=data['description '].apply(lambda x: word(x))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "5. Add a floor column:\n",
    "\n",
    "Extract the floor information from the \"floor_out_of\" column and add it as a separate column."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-7-afcf27eef58a>:13: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['floor']=data['floor_out_of'].apply(lambda x:get_floor(x) ).astype('int64')\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "array([11,  6,  2,  3,  7,  4, 13,  9, 14,  0,  1,  5, 10,  8, 19, 15, 25,\n",
       "       17, 12, 18, 29, 16, 20], dtype=int64)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def get_floor(x):\n",
    "    if isinstance(x, str):         \n",
    "        x_list=x.split()\n",
    "        if len(x_list)>1:\n",
    "            if x_list[1]=='קרקע' or x_list[1]=='מרתף': \n",
    "                return 0       # 'קומת קרקע/מרתף', 'קומת קרקע מתוך 5'\n",
    "            else:\n",
    "                return x_list[1]    # 'קומה 2 מתוך 4', 'קומה 6'\n",
    "        else:\n",
    "            return 0   # הגיוני שלא מילאו בגלל שהבית לא נמצא בבניין. לכן נמלא 0 \n",
    "    else:\n",
    "        return 0  # for nan # הגיוני שלא מילאו בגלל שהבית לא נמצא בבניין. לכן נמלא 0 \n",
    "data['floor']=data['floor_out_of'].apply(lambda x:get_floor(x) ).astype('int64')\n",
    "data['floor'].unique()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "6. Add a total_floors column:\n",
    "\n",
    "Calculate the total number of floors in the building and add it as a separate column."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-8-ec73e450e95d>:16: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['total_floors']=data['floor_out_of'].apply(lambda x: get_totalfloor(x)).astype('int64')\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "array([19,  9,  7,  6,  8, 24, 14, 16, 21, 28,  3,  0,  4,  2, 10,  5, 18,\n",
       "       20, 13,  1, 12, 30, 15, 26, 25, 17, 11, 27, 22], dtype=int64)"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def get_totalfloor(x):\n",
    "    if isinstance(x, str):         \n",
    "        x_list=x.split()\n",
    "        if len(x_list)==2:\n",
    "            if x_list[1]=='קרקע' or x_list[1]=='מרתף':   \n",
    "                return 0  # 'קומת קרקע'\n",
    "            else:\n",
    "                return x_list[1]   # 'קומה 6'\n",
    "        if len(x_list)==4:\n",
    "            return x_list[3]    # 'קומה 4 מתוך 6', 'קומת קרקע מתוך 5'\n",
    "            \n",
    "        else:\n",
    "            return 0   # הגיוני שלא מילאו בגלל שהבית לא נמצא בבניין. לכן נמלא 0 \n",
    "    else:\n",
    "        return 0  # for nan\n",
    "data['total_floors']=data['floor_out_of'].apply(lambda x: get_totalfloor(x)).astype('int64')\n",
    "data['total_floors'].unique()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "7. Create an \"entrance_date\" categorical column:\n",
    "\n",
    "Based on the current date, categorize the entrance date into one of the following categories:\n",
    "Less than 6 months\n",
    "6-12 months\n",
    "Above 1 year\n",
    "Flexible\n",
    "Not defined"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-9-aa2536bd2e8d>:24: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['entrance_date']=data['entranceDate '].apply(lambda x: entertime(x))\n"
     ]
    }
   ],
   "source": [
    "def entertime(x):\n",
    "    if isinstance(x, str):\n",
    "        x.strip()\n",
    "        if x=='גמיש':\n",
    "            return 'flexible'\n",
    "        if x=='לא צויין':\n",
    "            return 'not_defined'\n",
    "        if x=='מיידי':\n",
    "            return 'less_than_6_months'\n",
    "    \n",
    "    if isinstance(x, datetime.datetime):\n",
    "        today = datetime.date.today()\n",
    "        months_more_6 = today + datetime.timedelta(days=6*30)\n",
    "        months_more_12 = today + datetime.timedelta(days=12*30)\n",
    "        if x.date() < months_more_6:\n",
    "            return 'less_than_6_months'\n",
    "        if months_more_6 <= x.date() <= months_more_12:\n",
    "            return 'months_6_12'\n",
    "        if x.date() > months_more_12:\n",
    "            return 'above_year'    \n",
    "    \n",
    "    else:\n",
    "        return 'not_defined'\n",
    "data['entrance_date']=data['entranceDate '].apply(lambda x: entertime(x))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "8. Represent boolean fields (hasBalcony, hasMamad and other) as 0s and 1s:\n",
    "\n",
    "Convert all boolean fields to 0s and 1s, where 0 represents False and 1 represents True."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# הכנה ל 0 ו 1\n",
    "\n",
    "mappingdata = {\n",
    "    True: 1,\n",
    "    False: 0,\n",
    "    'לא': 0,\n",
    "    'כן': 1,\n",
    "    'yes': 1,\n",
    "    'יש': 1,\n",
    "    'אין': 0,\n",
    "    'no': 0,\n",
    "}\n",
    "\n",
    "data = data.apply(lambda x: x.replace(mappingdata))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0, 1])"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# טיפול ממ\"ד 0,1\n",
    "\n",
    "mappingMamad = {\n",
    "    'אין ממ״ד': 0,\n",
    "    'יש ממ״ד': 1,\n",
    "    'יש ממ\"ד': 1,\n",
    "    'אין ממ\"ד': 0\n",
    "}\n",
    "\n",
    "data['hasMamad '] = data['hasMamad '].replace(mappingMamad)\n",
    "data['hasMamad '] = data['hasMamad '].fillna(0)\n",
    "data['hasMamad '] = data['hasMamad '].astype(int)\n",
    "data['hasMamad '].unique()\n",
    "\n",
    "# טיפול במרפסת 0,1\n",
    "\n",
    "mappingBalcony = {\n",
    "    'אין מרפסת': 0,\n",
    "    'יש מרפסת': 1\n",
    "\n",
    "}\n",
    "\n",
    "data['hasBalcony '] = data['hasBalcony '].replace(mappingBalcony)\n",
    "data['hasBalcony '] = data['hasBalcony '].fillna(0)\n",
    "data['hasBalcony '].unique()\n",
    "# טיפול במיזוג אוויר 0,1\n",
    "\n",
    "mappingAC = {\n",
    "    'אין מיזוג אויר': 0,\n",
    "    'יש מיזוג אויר': 1,\n",
    "    'יש מיזוג אוויר': 1\n",
    "}\n",
    "\n",
    "data['hasAirCondition '] = data['hasAirCondition '].replace(mappingAC)\n",
    "data['hasAirCondition '].unique()\n",
    "# טיפול במעלית 0,1\n",
    "\n",
    "mappingElevator = {\n",
    "    'אין מעלית': 0,\n",
    "    'יש מעלית': 1}\n",
    "\n",
    "data['hasElevator '] = data['hasElevator '].replace(mappingElevator)\n",
    "data['hasElevator '].unique()\n",
    "\n",
    "# טיפול חניה 0,1\n",
    "\n",
    "mappingParking = {\n",
    "    'יש חניה': 1,\n",
    "    'יש חנייה': 1,\n",
    "    'אין חניה': 0}\n",
    "\n",
    "data['hasParking '] = data['hasParking '].replace(mappingParking)\n",
    "data['hasParking '].unique()\n",
    "\n",
    "mappingBars = {\n",
    "    'אין סורגים': 0,\n",
    "    'יש סורגים': 1\n",
    "}\n",
    "\n",
    "data['hasBars '] = data['hasBars '].replace(mappingBars)\n",
    "data['hasBars '] = data['hasBars '].fillna(0)\n",
    "data['hasBars '] = data['hasBars '].astype(int)\n",
    "data['hasBars '].unique()\n",
    "\n",
    "\n",
    "mappingStorage = {\n",
    "    'אין מחסן': 0,\n",
    "    'יש מחסן': 1\n",
    "}\n",
    "\n",
    "data['hasStorage '] = data['hasStorage '].replace(mappingStorage)\n",
    "data['hasStorage '] = data['hasStorage '].fillna(0)\n",
    "data['hasStorage '] = data['hasStorage '].astype(int)\n",
    "data['hasStorage '].unique()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([1, 0])"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mappingHandicap = {\n",
    "    True: 1,\n",
    "    False: 0,\n",
    "    'לא': 0,\n",
    "    'כן': 1,\n",
    "    'no': 0,\n",
    "    'yes': 1,\n",
    "    'לא נגיש לנכים': 0,\n",
    "    'נגיש לנכים': 1,\n",
    "    'נגיש': 1,\n",
    "    'לא נגיש': 0,\n",
    "}\n",
    "\n",
    "data['handicapFriendly '] = data['handicapFriendly '].replace(mappingHandicap)\n",
    "data['handicapFriendly '] = data['handicapFriendly '].fillna(0)\n",
    "data['handicapFriendly '] = data['handicapFriendly '].astype(int)\n",
    "data['handicapFriendly '].unique()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "ניקיון נוסף וסידור לדאטה לפני בניית המודל  "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>City</th>\n",
       "      <th>type</th>\n",
       "      <th>room_number</th>\n",
       "      <th>Area</th>\n",
       "      <th>Street</th>\n",
       "      <th>number_in_street</th>\n",
       "      <th>city_area</th>\n",
       "      <th>price</th>\n",
       "      <th>num_of_images</th>\n",
       "      <th>floor_out_of</th>\n",
       "      <th>...</th>\n",
       "      <th>hasBalcony</th>\n",
       "      <th>hasMamad</th>\n",
       "      <th>handicapFriendly</th>\n",
       "      <th>entranceDate</th>\n",
       "      <th>furniture</th>\n",
       "      <th>publishedDays</th>\n",
       "      <th>description</th>\n",
       "      <th>floor</th>\n",
       "      <th>total_floors</th>\n",
       "      <th>entrance_date</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>5.5</td>\n",
       "      <td>137</td>\n",
       "      <td>רפאלי שרגא</td>\n",
       "      <td>3</td>\n",
       "      <td>אם המושבות החדשה</td>\n",
       "      <td>3600000</td>\n",
       "      <td>6.0</td>\n",
       "      <td>קומה 11 מתוך 19</td>\n",
       "      <td>...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>7</td>\n",
       "      <td>למכירה 5 5 חדרים ענקית מרווחת מוארת קומה גבוהה...</td>\n",
       "      <td>11</td>\n",
       "      <td>19</td>\n",
       "      <td>flexible</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>3</td>\n",
       "      <td>84</td>\n",
       "      <td>כצנלסון אהרון</td>\n",
       "      <td>6</td>\n",
       "      <td>נווה גן</td>\n",
       "      <td>2550000</td>\n",
       "      <td>6.0</td>\n",
       "      <td>קומה 6 מתוך 9</td>\n",
       "      <td>...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>מיידי</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>8</td>\n",
       "      <td>למכירה מפרטי ברחוב אהרון כצנלסון השקט והמבוקש ...</td>\n",
       "      <td>6</td>\n",
       "      <td>9</td>\n",
       "      <td>less_than_6_months</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>4</td>\n",
       "      <td>120</td>\n",
       "      <td>הירקונים</td>\n",
       "      <td>17</td>\n",
       "      <td>קרית הרב סלומון</td>\n",
       "      <td>2650000</td>\n",
       "      <td>10.0</td>\n",
       "      <td>קומה 2 מתוך 7</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>חלקי</td>\n",
       "      <td>6</td>\n",
       "      <td>פריים לוקשיין בשכונת שיפר המאוד מבוקשת למכירה ...</td>\n",
       "      <td>2</td>\n",
       "      <td>7</td>\n",
       "      <td>flexible</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>3.5</td>\n",
       "      <td>110</td>\n",
       "      <td>סלנט שמואל</td>\n",
       "      <td>56</td>\n",
       "      <td>המרכז השקט</td>\n",
       "      <td>2450000</td>\n",
       "      <td>8.0</td>\n",
       "      <td>קומה 2 מתוך 6</td>\n",
       "      <td>...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>חלקי</td>\n",
       "      <td>8</td>\n",
       "      <td>בפתח תקווה ברחוב שמואל סלנט המבוקשלא כדאי לפספ...</td>\n",
       "      <td>2</td>\n",
       "      <td>6</td>\n",
       "      <td>flexible</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>פתח תקווה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>4.5</td>\n",
       "      <td>120</td>\n",
       "      <td>בן צבי יצחק</td>\n",
       "      <td>28</td>\n",
       "      <td>כפר גנים ב</td>\n",
       "      <td>2720000</td>\n",
       "      <td>9.0</td>\n",
       "      <td>קומה 3 מתוך 6</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>21</td>\n",
       "      <td>הדירה משופצת חלקית בטעם טוב פונה לעורף לכיוון ...</td>\n",
       "      <td>3</td>\n",
       "      <td>6</td>\n",
       "      <td>flexible</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>694</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>בית פרטי</td>\n",
       "      <td>9.5 חד׳</td>\n",
       "      <td>350</td>\n",
       "      <td>הורד</td>\n",
       "      <td>35</td>\n",
       "      <td></td>\n",
       "      <td>8200000</td>\n",
       "      <td>NaN</td>\n",
       "      <td>קומה 4 מתוך 4</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>בית גדול מאוד 3 כיווני אוויר 2 מרפסות גדולות</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>flexible</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>695</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>4 חד׳</td>\n",
       "      <td>110</td>\n",
       "      <td>קזן</td>\n",
       "      <td>NaN</td>\n",
       "      <td>מרכז דרום</td>\n",
       "      <td>3350000</td>\n",
       "      <td>6.0</td>\n",
       "      <td>קומה 4 מתוך 6</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>גמיש</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>NaN</td>\n",
       "      <td>בקומה 4 הדירה 110 מר נטו136 מר ארנונה מעוצבת ל...</td>\n",
       "      <td>4</td>\n",
       "      <td>6</td>\n",
       "      <td>flexible</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>696</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>קוטג'</td>\n",
       "      <td>7 חד׳</td>\n",
       "      <td>376</td>\n",
       "      <td>הטללים</td>\n",
       "      <td>NaN</td>\n",
       "      <td>קרית גנים</td>\n",
       "      <td>8500000</td>\n",
       "      <td>13.0</td>\n",
       "      <td>קומת קרקע</td>\n",
       "      <td>...</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2023-08-01 00:00:00</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>NaN</td>\n",
       "      <td>במערב המבוקש ה בית הנדיר הזה הוא עוד אחד מה הי...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>less_than_6_months</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>697</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>5 חד׳</td>\n",
       "      <td>126</td>\n",
       "      <td>אחד העם</td>\n",
       "      <td>NaN</td>\n",
       "      <td>לסטר</td>\n",
       "      <td>3850000</td>\n",
       "      <td>NaN</td>\n",
       "      <td>קומה 5 מתוך 7</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>מיידי</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>NaN</td>\n",
       "      <td>דירה חדשה מהקבלן באזור מבוקש 5 חדרים מרווחת ומ...</td>\n",
       "      <td>5</td>\n",
       "      <td>7</td>\n",
       "      <td>less_than_6_months</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>698</th>\n",
       "      <td>רעננה</td>\n",
       "      <td>דירה</td>\n",
       "      <td>4.5 חד׳</td>\n",
       "      <td>140</td>\n",
       "      <td>קזן</td>\n",
       "      <td>10</td>\n",
       "      <td>מרכז דרום</td>\n",
       "      <td>3730000</td>\n",
       "      <td>6.0</td>\n",
       "      <td>קומה 3 מתוך 6</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>2024-02-01 00:00:00</td>\n",
       "      <td>לא צויין</td>\n",
       "      <td>NaN</td>\n",
       "      <td>לא למתווכים ללא תיווך מתווכים לא להתקשר דירה ע...</td>\n",
       "      <td>3</td>\n",
       "      <td>6</td>\n",
       "      <td>months_6_12</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>693 rows × 26 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          City      type room_number  Area         Street number_in_street  \\\n",
       "0    פתח תקווה      דירה         5.5   137     רפאלי שרגא                3   \n",
       "1    פתח תקווה      דירה           3    84  כצנלסון אהרון                6   \n",
       "2    פתח תקווה      דירה           4   120       הירקונים               17   \n",
       "3    פתח תקווה      דירה         3.5   110     סלנט שמואל               56   \n",
       "4    פתח תקווה      דירה         4.5   120    בן צבי יצחק               28   \n",
       "..         ...       ...         ...   ...            ...              ...   \n",
       "694      רעננה  בית פרטי     9.5 חד׳   350           הורד               35   \n",
       "695      רעננה      דירה       4 חד׳   110            קזן              NaN   \n",
       "696      רעננה     קוטג'       7 חד׳   376         הטללים              NaN   \n",
       "697      רעננה      דירה       5 חד׳   126        אחד העם              NaN   \n",
       "698      רעננה      דירה     4.5 חד׳   140            קזן               10   \n",
       "\n",
       "            city_area    price  num_of_images     floor_out_of  ...  \\\n",
       "0    אם המושבות החדשה  3600000            6.0  קומה 11 מתוך 19  ...   \n",
       "1             נווה גן  2550000            6.0    קומה 6 מתוך 9  ...   \n",
       "2     קרית הרב סלומון  2650000           10.0    קומה 2 מתוך 7  ...   \n",
       "3          המרכז השקט  2450000            8.0    קומה 2 מתוך 6  ...   \n",
       "4          כפר גנים ב  2720000            9.0    קומה 3 מתוך 6  ...   \n",
       "..                ...      ...            ...              ...  ...   \n",
       "694                    8200000            NaN    קומה 4 מתוך 4  ...   \n",
       "695         מרכז דרום  3350000            6.0    קומה 4 מתוך 6  ...   \n",
       "696         קרית גנים  8500000           13.0        קומת קרקע  ...   \n",
       "697              לסטר  3850000            NaN    קומה 5 מתוך 7  ...   \n",
       "698         מרכז דרום  3730000            6.0    קומה 3 מתוך 6  ...   \n",
       "\n",
       "     hasBalcony   hasMamad   handicapFriendly         entranceDate   \\\n",
       "0            0.0          1                  1                 גמיש   \n",
       "1            0.0          1                  0                מיידי   \n",
       "2            1.0          1                  0                 גמיש   \n",
       "3            0.0          1                  1                 גמיש   \n",
       "4            1.0          1                  1                 גמיש   \n",
       "..           ...        ...                ...                  ...   \n",
       "694          1.0          1                  0                 גמיש   \n",
       "695          1.0          1                  1                 גמיש   \n",
       "696          0.0          0                  0  2023-08-01 00:00:00   \n",
       "697          1.0          1                  1                מיידי   \n",
       "698          1.0          1                  1  2024-02-01 00:00:00   \n",
       "\n",
       "    furniture   publishedDays   \\\n",
       "0     לא צויין               7   \n",
       "1     לא צויין               8   \n",
       "2         חלקי               6   \n",
       "3         חלקי               8   \n",
       "4     לא צויין              21   \n",
       "..         ...             ...   \n",
       "694          0             NaN   \n",
       "695   לא צויין             NaN   \n",
       "696   לא צויין             NaN   \n",
       "697   לא צויין             NaN   \n",
       "698   לא צויין             NaN   \n",
       "\n",
       "                                          description   floor  total_floors  \\\n",
       "0    למכירה 5 5 חדרים ענקית מרווחת מוארת קומה גבוהה...     11            19   \n",
       "1    למכירה מפרטי ברחוב אהרון כצנלסון השקט והמבוקש ...      6             9   \n",
       "2    פריים לוקשיין בשכונת שיפר המאוד מבוקשת למכירה ...      2             7   \n",
       "3    בפתח תקווה ברחוב שמואל סלנט המבוקשלא כדאי לפספ...      2             6   \n",
       "4    הדירה משופצת חלקית בטעם טוב פונה לעורף לכיוון ...      3             6   \n",
       "..                                                 ...    ...           ...   \n",
       "694       בית גדול מאוד 3 כיווני אוויר 2 מרפסות גדולות      4             4   \n",
       "695  בקומה 4 הדירה 110 מר נטו136 מר ארנונה מעוצבת ל...      4             6   \n",
       "696  במערב המבוקש ה בית הנדיר הזה הוא עוד אחד מה הי...      0             0   \n",
       "697  דירה חדשה מהקבלן באזור מבוקש 5 חדרים מרווחת ומ...      5             7   \n",
       "698  לא למתווכים ללא תיווך מתווכים לא להתקשר דירה ע...      3             6   \n",
       "\n",
       "          entrance_date  \n",
       "0              flexible  \n",
       "1    less_than_6_months  \n",
       "2              flexible  \n",
       "3              flexible  \n",
       "4              flexible  \n",
       "..                  ...  \n",
       "694            flexible  \n",
       "695            flexible  \n",
       "696  less_than_6_months  \n",
       "697  less_than_6_months  \n",
       "698         months_6_12  \n",
       "\n",
       "[693 rows x 26 columns]"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df= data.copy()\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([ nan,  3. ,  4. ,  5. ,  6. ,  8. ,  2. ,  5.5,  3.5,  2.5,  6.5,\n",
       "        4.5,  7.5,  7. ,  1. ,  9. ,  9.5, 10. ])"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# טיפול במספר חדרים ושינוי לעשרוני\n",
    "def room_number(x):\n",
    "    if isinstance(x, str):\n",
    "        x = re.sub(r'[^\\d\\.]', '', x)  # מחיקת תווים שאינם ספרות או פסיק\n",
    "        return x.replace(',', '')\n",
    "    elif isinstance(x, int):\n",
    "        return int(x) # חיזור ערך מספרי כמחרוזת\n",
    "    else:\n",
    "        return ''\n",
    "\n",
    "df['room_number']=df['room_number'].apply(lambda x: room_number(x)).replace('',np.nan).astype('float64')\n",
    "df['room_number'].unique()\n",
    "\n",
    "# טיפול בערך קיצוני- 35 חדרים\n",
    "df=df[df['room_number']!=35]\n",
    "df['room_number'].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-15-84bb97cf5f3c>:1: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['City']= df['City'].apply(lambda x: x.strip()).replace('נהרייה','נהריה')\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "array(['פתח תקווה', 'נתניה', 'באר שבע', 'הרצליה', 'אריאל', 'דימונה',\n",
       "       'רחובות', 'גבעת שמואל', 'ירושלים', 'שוהם', 'כפר סבא', 'רעננה',\n",
       "       'נהריה', 'זכרון יעקב', 'קרית ביאליק', 'חיפה', 'הוד השרון',\n",
       "       'תל אביב', 'ראשון לציון', 'יהוד מונוסון', 'נס ציונה', 'אילת',\n",
       "       'חולון', 'מודיעין מכבים רעות', 'צפת', 'בת ים', 'רמת גן',\n",
       "       'נוף הגליל', 'בית שאן'], dtype=object)"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['City']= df['City'].apply(lambda x: x.strip()).replace('נהרייה','נהריה')\n",
    "df['City'].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-16-b709617b2f53>:2: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['condition '] = np.where((df['condition '] == 'None') | (df['condition '] == False), np.nan, df['condition '])\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "array(['שמור', 'חדש', 'משופץ', 'לא צויין', 'ישן', 'דורש שיפוץ', nan],\n",
       "      dtype=object)"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#לסדר את עמודת מצב הנכס - condition\n",
    "df['condition '] = np.where((df['condition '] == 'None') | (df['condition '] == False), np.nan, df['condition '])\n",
    "df['condition '].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-17-10b9b30d5e50>:9: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['number_in_street'] = df['number_in_street'].apply(clean_number_in_street).replace('', np.nan)\n",
      "<ipython-input-17-10b9b30d5e50>:10: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df['number_in_street'] = pd.to_numeric(df['number_in_street'], errors='coerce').astype('Int64')\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<IntegerArray>\n",
       "[   3,    6,   17,   56,   28,    2,   18,    1,   23, <NA>,   27,    4,   71,\n",
       "    8,   37,    9,   29,   85,   46,   13,    7,   15,   26,   14,   35,   44,\n",
       "   36,   16,   34,   22,  123,  217,  105,   82,  131,  144,   42,   10,   12,\n",
       "   25,   53,   20,    5,   24,   40,   49,    0,   21,   59,   86,  121,   81,\n",
       "   78, 2003,   69,   11,   65,   57,   94,   32,  145,  221,   79,   19,   33,\n",
       "   52,   43,   50,   61,  110,   70,   63,   80,   68,   30,  342,   39,   41,\n",
       "  201, 2110,  200,  575,   72,  142,  264,  329,   47,  116,   58,   54,  212]\n",
       "Length: 91, dtype: Int64"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def clean_number_in_street(x):\n",
    "    if isinstance(x, str):\n",
    "        x = re.sub(r'[^\\d,]', '', x)  # מחיקת תווים שאינם ספרות או פסיק\n",
    "        return x.replace(',', '')  # הסרת פסיקים\n",
    "    elif isinstance(x, int):\n",
    "        return str(x)  # חיזור ערך מספרי כמחרוזת\n",
    "    else:\n",
    "        return ''\n",
    "df['number_in_street'] = df['number_in_street'].apply(clean_number_in_street).replace('', np.nan)\n",
    "df['number_in_street'] = pd.to_numeric(df['number_in_street'], errors='coerce').astype('Int64')\n",
    "df['number_in_street'].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "#הורדת עמודות שהפכנו לעמודות אחרות\n",
    "df = df.drop(['floor_out_of','entranceDate ','publishedDays '],axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = df.dropna(subset = ['condition '])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "City                   0\n",
       "floor                  0\n",
       "description            0\n",
       "furniture              0\n",
       "handicapFriendly       0\n",
       "hasMamad               0\n",
       "hasBalcony             0\n",
       "condition              0\n",
       "hasStorage             0\n",
       "total_floors           0\n",
       "hasBars                0\n",
       "price                  0\n",
       "city_area              0\n",
       "Street                 0\n",
       "type                   0\n",
       "entrance_date          0\n",
       "hasElevator            1\n",
       "hasAirCondition        1\n",
       "hasParking             1\n",
       "num_of_images          8\n",
       "Area                  16\n",
       "room_number           62\n",
       "number_in_street     217\n",
       "dtype: int64"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.isnull().sum().sort_values()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "df.drop(columns='description ', inplace=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
